version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
<<<<<<< HEAD
    labels:
      - tag:bot
      - type:github-actions
=======
>>>>>>> de2053b (ci: add CI (#5))
