<<<<<<< HEAD
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for all rules.
=======
>>>>>>> de2053b (ci: add CI (#5))
default: true
MD013: false
MD024:
  siblings_only: true
<<<<<<< HEAD
MD029:
  style: ordered
MD033: false
MD041: false
MD045: false
MD046: false
MD049: false
=======
MD033: false
MD041: false
MD046: false
>>>>>>> de2053b (ci: add CI (#5))
