ci:
<<<<<<< HEAD
  autofix_commit_msg: "style(pre-commit): autofix"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
=======
  autofix_commit_msg: "ci(pre-commit): autofix"
  autoupdate_commit_msg: "ci(pre-commit): autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
>>>>>>> de2053b (ci: add CI (#5))
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/igorshubovych/markdownlint-cli
<<<<<<< HEAD
    rev: v0.41.0
=======
    rev: v0.30.0
>>>>>>> de2053b (ci: add CI (#5))
    hooks:
      - id: markdownlint
        args: [-c, .markdownlint.yaml, --fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
<<<<<<< HEAD
    rev: v4.0.0-alpha.8
=======
    rev: v2.5.0
>>>>>>> de2053b (ci: add CI (#5))
    hooks:
      - id: prettier

  - repo: https://github.com/adrienverge/yamllint
<<<<<<< HEAD
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
=======
    rev: v1.26.3
    hooks:
      - id: yamllint
        exclude: .*.param.yaml

  - repo: https://github.com/tier4/pre-commit-hooks-ros
    rev: v0.4.0
    hooks:
      - id: prettier-package-xml
      - id: sort-package-xml

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.1
>>>>>>> de2053b (ci: add CI (#5))
    hooks:
      - id: shellcheck

  - repo: https://github.com/scop/pre-commit-shfmt
<<<<<<< HEAD
    rev: v3.9.0-1
=======
    rev: v3.4.1-1
>>>>>>> de2053b (ci: add CI (#5))
    hooks:
      - id: shfmt
        args: [-w, -s, -i=4]

<<<<<<< HEAD
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
=======
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
        args: [--line-length=100]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-blind-except,
            flake8-builtins,
            flake8-class-newline,
            flake8-comprehensions,
            flake8-deprecated,
            flake8-docstrings,
            flake8-import-order,
            flake8-quotes,
          ]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1
    hooks:
      - id: clang-format

  - repo: https://github.com/cpplint/cpplint
    rev: 1.5.5
    hooks:
      - id: cpplint
        args: [--quiet]
        exclude: .cu
>>>>>>> de2053b (ci: add CI (#5))

exclude: .svg
