printWidth: 100
tabWidth: 2
<<<<<<< HEAD
overrides:
  - files: package.xml
    options:
      printWidth: 1000
      xmlSelfClosingSpace: false
      xmlWhitespaceSensitivity: ignore

  - files: "*.launch.xml"
    options:
      printWidth: 200
      xmlSelfClosingSpace: false
      xmlWhitespaceSensitivity: ignore

  - files: "*.xacro"
    options:
      printWidth: 200
      xmlSelfClosingSpace: false
      xmlWhitespaceSensitivity: ignore
=======
>>>>>>> de2053b (ci: add CI (#5))
