/**:
  ros__parameters:
    lanelet2_map_projector_type: UTM   # Options: MGRS, UTM   #HH_230215 # MGRS
    latitude: 36.122714332693775        # Latitude of map_origin, using in UTM
    longitude: 126.77664951822946       # Longitude of map_origin, using in UTM

    center_line_resolution: 5.0         # [m]
