/**:
  ros__parameters:
    use_steer_ff: true
    use_steer_fb: true
    is_debugging: false
    steer_pid:
      kp: 100.0 # HH_230602
      ki: 0.5
      kd: 0.0
      max: 10.0
      min: -10.0
      max_p: 100.0 # HH_230602
      min_p: -100.0 # HH_230602
      max_i: 1.0
      min_i: -1.0
      max_d: 0.0
      min_d: 0.0
      invalid_integration_decay: 0.97
