/**: # HH_230605
  ros__parameters:
    min_longitudinal_offset: 1.75
    max_longitudinal_offset: 2.25
    min_lateral_offset: -1.3
    max_lateral_offset: 1.3
    min_height_offset: 1.0
    max_height_offset: 1.2
