/**:
  ros__parameters:

    # Latitude of local origin
    latitude: 360965.999225

    # Longitude of local origin
    longitude: 4065972.492659

    # Altitude of local origin
    altitude: 100.878965