/**:
  ros__parameters:
    camera_name: "camera_top" # HH_250213
    frame_id: "traffic_light_camera/camera_link" # HH_250213
    pixel_format: bgr24 # HH_250213
    serial_no: 212401044 # HH_250213
    camera_info_url: "file:///home/a/ros2_ws/src/lucid_vision_driver/config/test.yaml" # HH_250213
    fps: 20 # HH_250213
    horizontal_binning: 1 # resize horizontal resolution/horizontal_binning
    vertical_binning: 1 # resize horizontal resolution/vertical_binning
    enable_rectifying: true
    enable_compressing: true
    use_default_device_settings: true
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: true
    exposure_target: 187
    gain_auto: true
    gain_target: 10
    gamma_target: 1.0
    image_horizontal_flip: false
    image_vertical_flip: false


